#!/bin/bash

# Happy ssh agent forwarding for tmux/screen
# Based on https://werat.github.io/2017/02/04/tmux-ssh-agent-forwarding.html
#
if [ ! -S ~/.ssh/ssh_auth_sock ] && [ -S "$SSH_AUTH_SOCK" ]; then
  ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi


# Might fix the ``X11 connection uses different authentication protocol.``
# Based on reply from https://superuser.com/questions/492289/x11-connection-uses-different-authentication-protocol-when-using-ssh-x
if read proto cookie && [ -n "$DISPLAY" ]; then
    if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
        # X11UseLocalhost=yes
        echo add unix:`echo $DISPLAY | cut -c11-` $proto $cookie
    else
        # X11UseLocalhost=no
        echo add $DISPLAY $proto $cookie
    fi | xauth -q -
fi
