#! /bin/sh

# AutostartA
xset r rate 200 50 &
synclient TouchpadOff=1 &
sxhkd -c ~/.config/sxhkd/sxhkdrc &

bspc monitor -d I II III IV V VI VII VIII IX

# Styling
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a TelegramDesktop desktop='^5'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Start additional tools
polybar -c ~/.config/polybar/config.ini main &
telegram-desktop &
synergy &
netctl-gui --minimized &
udiskie -t &
volumeicon &
alacritty &
blueman-tray &
